### ISSUE TITLE
supplementalGroups

### ISSUE THREAD

**Issue by chrisns** [kubewarden/user-group-psp-policy#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yaml
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: supplementalgroups
spec:
  policyServer: default
  module: registry://ghcr.io/kubewarden/policies/user-group-psp:v0.1.5
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
  settings:
    supplemental_groups: 
      rule: "MustRunAs"
      ranges:
        - min: 100
          max: 200
```
does not block
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-supplementalgroups-disallowed
  labels:
    app: nginx-users
spec:
  securityContext:
    supplementalGroups:
      - 250
  containers:
    - name: nginx
      image: nginx
```

### Expected Behavior

pod should be rejected

### Environment

```markdown
- OS:
- Architecture:
```

**Comment by viccuad** [comment]
It seems that the policy definition is just missing:
```
 settings:
    run_as_user:
      rule: "RunAsAny"
    run_as_group:
      rule: "RunAsAny"
```

With that, the pod gets rejected as expected.

From the [definition of the PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups), there doesn't seem to be a default value for their `RunAsUser` and `RunAsGroup`, so I suppose their intent is to be explicit, and we are just copying that intent in this policy.
