### ISSUE TITLE
unwanted mutations

### ISSUE THREAD

**Issue by chrisns** [kubewarden/user-group-psp-policy#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The policy attempted to mutate the request, but it is currently configured to not allow mutations

### Expected Behavior

- I expect it to not try to mutate if i've not set it to

- I expect it to not need to mutate the overall pod securitycontext.runasuser given there are no containers in the pod that breach the policy

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-allowed
  labels:
    app: nginx-users
spec:
  securityContext:
    runAsUser: 100
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 150
```
is allowed as expected

### Steps To Reproduce

policy:
```yaml
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: psp-usergroup-f93a4
spec:
  module: registry://ghcr.io/kubewarden/policies/user-group-psp:v0.4.9
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
      operations:
        - CREATE
        - UPDATE
  mutating: false
  settings:
    run_as_user:
      rule: MustRunAs
      ranges:
        - min: 100
          max: 200
    supplemental_groups:
      rule: RunAsAny
```

expected allowed.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-users-allowed
  labels:
    app: nginx-users
spec:
  securityContext:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsUser: 150
```

```
Error from server: error when creating "allowed.yaml": admission webhook "clusterwide-psp-usergroup-f93a4.kubewarden.admission" denied the request: Request rejected by policy clusterwide-psp-usergroup-f93a4. The policy attempted to mutate the request, but it is currently configured to not allow mutations.
```

### Environment

```markdown
- OS: osx
- Architecture: arm64
```

### Anything else?

same applies to groups
