### ISSUE TITLE
Mutation is forced even when flag is set to false

### ISSUE THREAD

**Issue by anishnagaraj** [kubewarden/user-group-psp-policy#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Though I have my `mutating` flag set to false, the policy attempts to mutate and hence disallows a valid resource to be created. I was expecting this to be closed through v0.5.0 version.

### Expected Behavior

The policy should not attempt to mutate when the `mutating` flag is set to `false`

### Steps To Reproduce

Following is my policy:

```
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: PSP
    io.kubewarden.policy.severity: medium
  name: do-not-run-as-root
spec:
  backgroundAudit: true
  mode: protect #possible values: monitor & protect
  module: ghcr.io/kubewarden/policies/user-group-psp:v0.5.0 #v0.4.9
  mutating: false
  policyServer: policies-server
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - replicationcontrollers
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
    - cronjobs
  settings:
    run_as_group:
      rule: RunAsAny
    run_as_user:
      rule: MustRunAsNonRoot
    supplemental_groups:
      rule: RunAsAny
  timeoutSeconds: 10

```
Following is my resource(do-not-run-as-root-allowed.yaml)

```
apiVersion: v1
kind: Pod
metadata:
  name: root-pod
  namespace: demo-kubewarden
spec:
  containers:
  - name: root-container
    image: nginx
    securityContext:
      runAsUser: 150  # This is the UID for the root user

```

Expected result:
The resource should be applied

Actual result:
```Error from server: error when creating "do-not-run-as-root-allowed.yaml": admission webhook "clusterwide-do-not-run-as-root.kubewarden.admission" denied the request: Request rejected by policy clusterwide-do-not-run-as-root. The policy attempted to mutate the request, but it is currently configured to not allow mutations.```

### Environment

```markdown
- OS: osx
- Architecture: arm64
```
